# Generated by Django 5.2.7 on 2025-10-23 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('dificultad', models.IntegerField(default=1)),
                ('filas', models.IntegerField(default=2)),
                ('columnas', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Estadistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_partidas', models.IntegerField(default=0)),
                ('victorias', models.IntegerField(default=0)),
                ('derrotas', models.IntegerField(default=0)),
                ('promedio_intentos', models.FloatField(default=0.0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('simbolo', models.CharField(blank=True, max_length=10, null=True)),
                ('posicion', models.IntegerField()),
                ('valor', models.CharField(blank=True, max_length=100, null=True)),
                ('revelada', models.BooleanField(default=False)),
                ('emparejada', models.BooleanField(default=False)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memory_game.nivel')),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('ganada', models.BooleanField(default=False)),
                ('movimientos', models.IntegerField(default=0)),
                ('aciertos', models.IntegerField(default=0)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memory_game.nivel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Intento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_correcto', models.BooleanField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('carta1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carta1', to='memory_game.carta')),
                ('carta2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carta2', to='memory_game.carta')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memory_game.partida')),
            ],
        ),
        migrations.AddField(
            model_name='carta',
            name='partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memory_game.partida'),
        ),
    ]
