# Generated by Django 5.2.7 on 2025-10-23 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carta',
            name='partida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='memory_game.partida'),
        ),
    ]
