# Generated by Django 5.2.7 on 2025-10-29 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_game', '0002_alter_carta_partida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estadistica',
            name='intentos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estadistica',
            name='nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='memory_game.nivel'),
        ),
        migrations.AddField(
            model_name='estadistica',
            name='pares_encontrados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estadistica',
            name='tiempo',
            field=models.CharField(default='00:00', max_length=10),
        ),
        migrations.AddField(
            model_name='intento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estadistica',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='intento',
            name='carta1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carta1', to='memory_game.carta'),
        ),
        migrations.AlterField(
            model_name='intento',
            name='carta2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carta2', to='memory_game.carta'),
        ),
        migrations.AlterField(
            model_name='intento',
            name='es_correcto',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='intento',
            name='partida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='memory_game.partida'),
        ),
    ]
